- hosts: all
  become: yes
  tasks:

    #https://kubernetes.io/docs/setup/production-environment/container-runtimes/#docker
    #instalar docker para k8s
    - name: Install required packages
      yum:
        update_cache: yes
        name: "{{ packages }}"
      vars:
        packages:
            - yum-utils
            - device-mapper-persistent-data
            - lvm2    
    
    - name: Add Docker repository
      shell: yum-config-manager --add-repo  https://download.docker.com/linux/centos/docker-ce.repo
 
    
    - name: Install Docker CE.
      yum:
        update_cache: yes
        name: "{{ packages }}"
      vars:
        packages:
            - containerd.io-1.2.13
            - docker-ce-19.03.8
            - docker-ce-cli-19.03.8

    - name: Create /etc/docker directory.
      file:
        path: /etc/docker
        state: directory

    - name: Setup daemon.
      shell:
        cmd: |
            cat > /etc/docker/daemon.json <<EOF
            {
                "exec-opts": ["native.cgroupdriver=systemd"],
                "log-driver": "json-file",
                "log-opts": {
                    "max-size": "100m"
                },
                "storage-driver": "overlay2",
                "storage-opts": [
                    "overlay2.override_kernel_check=true"
                ]
            }
            EOF

    - name: create docker.service.d
      file:
        path: /etc/systemd/system/docker.service.d
        state: directory

    - name: Restart Docker
      systemd:
        daemon_reload: yes
        enabled: yes
        name: docker
        state: restarted